package com.janey.bookstuff.tbr.data

import com.janey.bookstuff.database.entities.TBRBookEntity
import kotlinx.coroutines.flow.Flow

interface TBRRepository {
    suspend fun getBooks(): Flow<List<TBRBookEntity>>
    suspend fun getBookById(id: Long): Flow<TBRBookEntity?>

    /**
     * Insert the given book into the database
     * @param book book to save
     * @return autogenerated id of the saved entry
     */
    suspend fun insertBook(book: TBRBookEntity): Long
    suspend fun updateBook(book: TBRBookEntity)
}